name: Deploy to github pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.*md'
      - '**/.gitignore'

jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            version:  12.x
        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Install dependencies (npm ci)
          run: npm ci
    
        - name: Build
          run: npm run build
          env:
            CI: false
            REACT_APP_DEFAULT_URL: https://raw.githubusercontent.com/layik/eatlas-data/main/casualties.csv 
            REACT_APP_MAPBOX_ACCESS_TOKEN: ${{secrets.MAPBOX_KEY}}

        - name: Run deploy script
          run: |
            git config user.name "layik" && git config user.email "layik.hama@gmail.com"
            git checkout --orphan gh-pages
            git --work-tree build add --all
            git --work-tree build commit -m 'Deploy'
            git push origin HEAD:gh-pages --force

