name: Node CI

on:
  push:
    paths-ignore:
      - '**/README.*md'
      - '**/change*.md'
      - 'notes/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm i
      env:
        CI: true
    - name: install react & react-dom
      run: npm i react react-dom
    - name: npm test
      run: npm test
