name: Node CI

on:
  push:
    paths-ignore:
      - '**/README.*md'
      - '**/change*.md'
      - 'notes/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn
      env:
        CI:

    - name: install react & react-dom
      run: yarn add react react-dom

    - name: Tests (cov)
      run: yarn run coverage

    - name: Codecov
      uses: codecov/codecov-action@v2
      if: ${{matrix.node-version == '14.x'}}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
